# -*- coding: utf-8 -*-
"""1-numberplate.ipynb

Automatically generated by Colaboratory.
By: Mathur from Tulas institute

Original file is located at
    https://colab.research.google.com/drive/1Pv9qeUe2OrFV34gJDGHGqMFvx18PdhFc
"""

!pip install easyocr

import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] = 8, 16

reader = easyocr.Reader(['en'])

Image("trial1.jpg")

output = reader.readtext("c")

output

cord = output[-1][0]

x_min, y_min = [int(min(idx)) for idx in zip(*cord)]

x_max, y_max = [int(max(idx)) for idx in zip(*cord)]

image = cv2.imread('/trial1.jpg')
cv2.rectangle(image,(x_min,y_min),(x_max,y_max),(0,0,255),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

#method 2 trail
!pip install tesseract
!pip install tesseract-ocr

!pip install pytesseract

from PIL import Image
import pytesseract
pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'

img1=Image.open("/trial1.jpg")
pytesseract.image_to_string(img1)